export type GitignoreTemplate = 'nodejs' | 'python' | 'rust' | 'go' | 'java' | 'none';

export const GITIGNORE_TEMPLATE_LABELS: Record<GitignoreTemplate, string> = {
  nodejs: 'Node.js',
  python: 'Python',
  rust: 'Rust',
  go: 'Go',
  java: 'Java',
  none: 'None',
};

const NODEJS_GITIGNORE = `# Dependencies
node_modules/

# Build output
dist/
build/
out/

# Environment
.env
.env.local
.env.*.local

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Runtime
.DS_Store
Thumbs.db

# Editor
.vscode/
.idea/
*.swp
*.swo

# Coverage
coverage/
.nyc_output/
`;

const PYTHON_GITIGNORE = `# Byte-compiled / optimised files
__pycache__/
*.py[cod]
*$py.class

# Virtual environments
venv/
.venv/
env/
.env/
ENV/

# Distribution / packaging
dist/
build/
*.egg-info/
*.egg
MANIFEST

# Testing
.pytest_cache/
.coverage
htmlcov/
.tox/

# Type checking
.mypy_cache/
.pyright/
.ruff_cache/

# Environment variables
.env
.env.local

# Editor
.vscode/
.idea/
*.swp

# OS
.DS_Store
Thumbs.db
`;

const RUST_GITIGNORE = `# Build output
target/

# Backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds
*.pdb

# Environment
.env
.env.local

# Editor
.vscode/
.idea/
*.swp

# OS
.DS_Store
Thumbs.db
`;

const GO_GITIGNORE = `# Build output
*.exe
*.exe~
*.dll
*.so
*.dylib
bin/

# Test binary
*.test

# Output of go coverage
*.out

# Go workspace
go.work
go.work.sum

# Module cache
vendor/

# Environment
.env
.env.local

# Editor
.vscode/
.idea/
*.swp

# OS
.DS_Store
Thumbs.db
`;

const JAVA_GITIGNORE = `# Compiled class files
*.class

# Log files
*.log

# Package files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Build output
target/
build/
out/
bin/

# Maven
.mvn/wrapper/maven-wrapper.jar

# Gradle
.gradle/
gradle/wrapper/gradle-wrapper.jar
!gradle/wrapper/gradle-wrapper.properties

# IDE
.vscode/
.idea/
*.iml
*.iws
*.ipr

# Test
test-output/

# Environment
.env
.env.local

# OS
.DS_Store
Thumbs.db
`;

export const GITIGNORE_TEMPLATES: Record<Exclude<GitignoreTemplate, 'none'>, string> = {
  nodejs: NODEJS_GITIGNORE,
  python: PYTHON_GITIGNORE,
  rust: RUST_GITIGNORE,
  go: GO_GITIGNORE,
  java: JAVA_GITIGNORE,
};

export function getGitignoreContent(template: GitignoreTemplate): string | null {
  if (template === 'none') return null;
  return GITIGNORE_TEMPLATES[template];
}
